# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "93dd6bd83d8241db95bf980d446f38b5"
name = "hide-price"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
handle = "hide-price-sabai-2024"

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
